package com.few_payments.transaction_service.transaction.service;

import com.few_payments.transaction_service.transaction.repository.UserRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.DefaultBlockParameterName;
import org.web3j.protocol.core.methods.response.EthGetBalance;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.tx.Transfer;
import org.web3j.utils.Convert;

import java.math.BigDecimal;

// Notes on the balance precision:
// The precision of "Wei" is 18 decimal places,
// which can lead to very long decimal numbers when converted to "Ether"
// (or "FEW" in our case).
// If the balance in the Genesis file or mined is set with a power of 2
// (e.g., 2^20), the conversion to Ether can produce a long decimal
// with many digits.
// To make it more readable, we can round it to 2 decimal places when
// displaying the balance. This is purely for display purposes and does
// not affect the actual balance in the blockchain, which is still stored
// with full precision in Wei.

import java.math.RoundingMode;

import org.web3j.crypto.Credentials;

/*
 * BlockchainService.java
 * Author: Edoardo Sabatini
 * Date: 2026-05-10
 * Latest Edit: 2026-05-11
 * Company: few-payments
 * Description: Service for interacting with the blockchain.
 */
@Service
public class BlockchainService {

    private final UserRepository userRepository;
    private final Web3j web3j;
    private final String masterWallet;

    // Spring injects the Web3j bean and the master wallet address from the configuration
    public BlockchainService(Web3j web3j, @Value("${blockchain.master-wallet}") String masterWallet, UserRepository userRepository) {
        this.web3j = web3j;
        this.masterWallet = masterWallet;
        this.userRepository = userRepository;
    }

    public BigDecimal getBalance() throws Exception {
        // Call to Geth to get the balance of the master wallet address
        EthGetBalance balanceResponse = web3j.ethGetBalance(masterWallet, DefaultBlockParameterName.LATEST)
                .sendAsync()
                .get();

        BigDecimal etherBalance = Convert.fromWei(balanceResponse.getBalance().toString(), Convert.Unit.ETHER);
        
        // Convert from Wei (the atomic unit) to Ether (FEW in our case)
        // We round it to 2 decimal places for better readability
        return etherBalance.setScale(2, RoundingMode.HALF_UP);
    }

    // This method executes a transfer of FEW from the master wallet to a specified address.
    public String transferFew(String toAddress, BigDecimal amountInFew, String privateKey) throws Exception {

        Credentials credentials = Credentials.create(privateKey);

        // It reads the chainId directly from the Geth node — no hardcoded value
        // 1. Load credentials from the private key
        long networkChainId = web3j.ethChainId().send().getChainId().longValueExact();

        // 2. We execute the actual transfer on Geth. The amount is converted from FEW to Wei (the atomic unit).
        // Convert.Unit.ETHER equivales to our "FEW" unit (18 decimals)
        Transfer transfer = new Transfer(
            web3j,
            new org.web3j.tx.FastRawTransactionManager(web3j, credentials, networkChainId)
        );

        // 3. I use the full version of sendFunds that accepts the chainId (EIP-155) to ensure 
        // compatibility with our private blockchain and prevent replay attacks across chains.
        TransactionReceipt receipt = transfer
            .sendFunds(toAddress, amountInFew, Convert.Unit.ETHER)
            .send();

        // 4. We return the transaction hash generated by the blockchain        
        return receipt.getTransactionHash();
    }

    // It returns the Web3j instance, which can be used to interact with the blockchain 
    // in other parts of the application (e.g., for balance checks, event listening, etc.)
    public Web3j getWeb3j() {
        return web3j;
    }

    // This method retrieves the balance of any given address, not just the master wallet.
    public BigDecimal getBalanceOf(String address) throws Exception {
        EthGetBalance balanceResponse = web3j.ethGetBalance(address, DefaultBlockParameterName.LATEST)
                .sendAsync()
                .get();

        return Convert.fromWei(balanceResponse.getBalance().toString(), Convert.Unit.ETHER)
                .setScale(2, RoundingMode.HALF_UP);
    }
}
